version: '3.8'
services:
  api:
    container_name: greencity-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greencity
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  db:
    image: postgres:13
    container_name: greencity-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greencity
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: greencity-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:6-alpine
    container_name: greencity-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
